---
# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apimappingconfig.edge-orchestrator.intel.com/v1
kind: APIMappingConfig
metadata:
  name: amc-orch-metadata-broker-openapi
  labels:
    configs.config.edge-orchestrator.intel.com: default
spec:
  specGenEnabled: true
  repoConf:
    url: "https://github.com/open-edge-platform/orch-metadata-broker.git"
    tag: "v0.4.1"
    specFilePath: "api/spec/openapi.yaml"
  mappings:
    - externalURI: /v1/projects/{projectName}/metadata
      serviceURI: metadata.orchestrator.apis/v1/metadata
  backend:
    service: "metadata-broker-orch-metadata-broker-rest.orch-ui.svc.cluster.local"
    port: 9988
