---
# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: apimappingconfig.edge-orchestrator.intel.com/v1
kind: APIMappingConfig
metadata:
  name: amc-cluster-manager-openapi
  labels:
    configs.config.edge-orchestrator.intel.com: default
spec:
  specGenEnabled: true
  repoConf:
    url: "https://github.com/open-edge-platform/cluster-manager.git"
    tag: "v0.1.34"
    specFilePath: "api/openapi/openapi.yaml"
  mappings:
    - externalURI: /v2/projects/{projectName}/clusters
      serviceURI: v2/clusters
    - externalURI: /v2/projects/{projectName}/clusters/summary
      serviceURI: v2/clusters/summary
    - externalURI: /v2/projects/{projectName}/clusters/{name}
      serviceURI: v2/clusters/{name}
    - externalURI: /v2/projects/{projectName}/clusters/{nodeId}/clusterdetail
      serviceURI: v2/clusters/{nodeId}/clusterdetail
    - externalURI: /v2/projects/{projectName}/clusters/{name}/nodes
      serviceURI: v2/clusters/{name}/nodes
    - externalURI: /v2/projects/{projectName}/clusters/{name}/nodes/{nodeId}
      serviceURI: v2/clusters/{name}/nodes/{nodeId}
    - externalURI: /v2/projects/{projectName}/clusters/{name}/labels
      serviceURI: v2/clusters/{name}/labels
    - externalURI: /v2/projects/{projectName}/clusters/{name}/template
      serviceURI: v2/clusters/{name}/template
    - externalURI: /v2/projects/{projectName}/clusters/{name}/kubeconfigs
      serviceURI: v2/clusters/{name}/kubeconfigs
    - externalURI: /v2/clusters/healthz
      serviceURI: /v2/healthz
    - externalURI: /v2/projects/{projectName}/templates
      serviceURI: v2/templates
    - externalURI: /v2/projects/{projectName}/templates/{name}/versions/{version}
      serviceURI: v2/templates/{name}/{version}
    - externalURI: /v2/projects/{projectName}/templates/{name}/default
      serviceURI: v2/templates/{name}/default
    - externalURI: /v2/projects/{projectName}/templates/{name}/versions
      serviceURI: v2/templates/{name}/versions
  backend:
    service: "cluster-manager.orch-cluster.svc.cluster.local"
    port: 8080
