apiVersion: v2
name: nexus-runtime
description: A Helm chart for Nexus master
version: 0.1.0
dependencies:
- name: nexus-api
  version: "0.0.1"
  repository: "file://../api/helm-chart"
- name: nexus-api-gw
  alias: api-gw
  version: "0.1.1"
  repository: "file://../api-gw/helm-chart"
