# Global values for the master chart
global:
  datamodelName: nexus-datamodel
  imagePullSecret: ""
  imagePullPolicy: "IfNotPresent"
  releaseTag: "latest"

nexus-api:
  image:
    repository: ghcr.io/ciscohyperdraive/oss-nexus-api
    tag: latest

api-gw:
  nexusApiGw:
    image:
      repository: ghcr.io/ciscohyperdraive/oss-nexus-api-gw
      tag: latest

  nexusK8sProxy:
    image:
      repository: ghcr.io/ciscohyperdraive/oss-nexus-k8s-proxy
      tag: latest
