// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by nexus. DO NOT EDIT.

package root_tsm_tanzu_vmware_com

const (
	GroupName = "root.tsm-tanzu.vmware.com"
)
