# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

misconfigurations:
  - id: AVD-KSV-0114
    paths:
      - "charts/vertical-pod-autoscaler/templates/cluster-role.yaml"
    statement: mutatingwebhookconfigurations required for VPA admission controller to inject pod resource recommendations

  - id: AVD-DS-0002
    paths:
      - "aws-sm-proxy/Dockerfile"
      - "cert-synchronizer/Dockerfile"
      - "keycloak-tenant-controller/images/Dockerfile"
      - "secrets/Dockerfile"
      - "squid-proxy/Dockerfile"
      - "token-fs/Dockerfile"
    statement: Distroless:nonroot images have no root user. USER command not required.

  - id: AVD-DS-0002
    paths:
      - "auth-service/Dockerfile"
    statement: Scratch images have no user. USER command would break the image.
