# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "**/go.sum",
  "**/*.md",
  "**/*.json",
  "**/*.http",
  "**/*.svg", "**/*.png", "**/*.ico",
  "**/*.txt",
  "**/VERSION",
  "**/.tool-versions",
  "tenancy-datamodel/IMAGE",
  "tenancy-datamodel/NAME",
  "nexus/TAG",
  "nexus/compiler/example/output/generated/nexus-gql/server",
  "nexus/docs/Nexus-Config-Propagation-Calculator.csv",
]
SPDX-FileCopyrightText = "2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
