// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// Code generated by nexus. DO NOT EDIT.

// +k8s:deepcopy-gen=package
// +groupName=project.tsm-tanzu.vmware.com
// +groupGoName=ProjectTsm

package v1
