// SPDX-FileCopyrightText: (C) 2025 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

// wire-graphql-resolvers rewrites the panic("not implemented") stubs that
// gqlgen writes into graph/schema.resolvers.go so that each resolver method
// delegates to the corresponding standalone get<Type><Field>Resolver helper
// generated by the nexus compiler into graph/graphqlResolver.go.
//
// Rewrite rules:
//   - Query root:   func (r *queryResolver) Root(ctx) (*model.T, error)
//                   -> return getRootResolver()
//   - Field:        func (r *<pkg>_<Node>Resolver) <Field>(ctx, obj *model.T, args...) (...)
//                   -> return get<T><Field>Resolver(obj, args...)
//
// Any resolver already implemented (body is not the standard panic stub) is
// left untouched.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"strings"
)

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintf(os.Stderr, "usage: %s <path/to/schema.resolvers.go>\n", os.Args[0])
		os.Exit(2)
	}
	path := os.Args[1]

	fset := token.NewFileSet()
	src, err := os.ReadFile(path)
	if err != nil {
		log.Fatalf("read %s: %v", path, err)
	}
	file, err := parser.ParseFile(fset, path, src, parser.ParseComments)
	if err != nil {
		log.Fatalf("parse %s: %v", path, err)
	}

	changed := 0
	for _, decl := range file.Decls {
		fn, ok := decl.(*ast.FuncDecl)
		if !ok || fn.Recv == nil || len(fn.Recv.List) != 1 {
			continue
		}
		if !isPanicNotImplemented(fn.Body) {
			continue
		}
		recvType := receiverTypeName(fn.Recv.List[0])
		newBody, ok := buildBody(recvType, fn)
		if !ok {
			continue
		}
		fn.Body = newBody
		changed++
	}

	if changed == 0 {
		log.Printf("wire-graphql-resolvers: no stubs to rewrite in %s", path)
		return
	}

	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, file); err != nil {
		log.Fatalf("print %s: %v", path, err)
	}
	if err := os.WriteFile(path, buf.Bytes(), 0o644); err != nil {
		log.Fatalf("write %s: %v", path, err)
	}
	log.Printf("wire-graphql-resolvers: rewired %d resolver(s) in %s", changed, path)
}

// isPanicNotImplemented returns true if the function body is exactly
// { panic(fmt.Errorf("not implemented: ...")) }.
func isPanicNotImplemented(body *ast.BlockStmt) bool {
	if body == nil || len(body.List) != 1 {
		return false
	}
	es, ok := body.List[0].(*ast.ExprStmt)
	if !ok {
		return false
	}
	call, ok := es.X.(*ast.CallExpr)
	if !ok {
		return false
	}
	ident, ok := call.Fun.(*ast.Ident)
	if !ok || ident.Name != "panic" || len(call.Args) != 1 {
		return false
	}
	inner, ok := call.Args[0].(*ast.CallExpr)
	if !ok {
		return false
	}
	sel, ok := inner.Fun.(*ast.SelectorExpr)
	if !ok {
		return false
	}
	pkg, ok := sel.X.(*ast.Ident)
	if !ok || pkg.Name != "fmt" || sel.Sel.Name != "Errorf" {
		return false
	}
	if len(inner.Args) < 1 {
		return false
	}
	lit, ok := inner.Args[0].(*ast.BasicLit)
	if !ok {
		return false
	}
	return strings.Contains(lit.Value, "not implemented")
}

// receiverTypeName returns the base identifier of the receiver type (strips
// pointer wrapper).
func receiverTypeName(field *ast.Field) string {
	switch t := field.Type.(type) {
	case *ast.StarExpr:
		if id, ok := t.X.(*ast.Ident); ok {
			return id.Name
		}
	case *ast.Ident:
		return t.Name
	}
	return ""
}

// buildBody constructs the replacement body for a stub resolver, returning
// (nil, false) if the method does not match a shape we know how to wire.
func buildBody(recvType string, fn *ast.FuncDecl) (*ast.BlockStmt, bool) {
	// Query root resolver: func (r *queryResolver) Root(ctx) (*model.T, error)
	if recvType == "queryResolver" && fn.Name.Name == "Root" {
		return returnCall("getRootResolver"), true
	}

	// Field resolvers: func (r *<foo>Resolver) <Field>(ctx, obj *model.T, args...)
	if !strings.HasSuffix(recvType, "Resolver") {
		return nil, false
	}
	if fn.Type.Params == nil || len(fn.Type.Params.List) < 2 {
		return nil, false
	}
	// params[0] = ctx, params[1] = obj *model.T
	objField := fn.Type.Params.List[1]
	if len(objField.Names) != 1 {
		return nil, false
	}
	objName := objField.Names[0].Name
	star, ok := objField.Type.(*ast.StarExpr)
	if !ok {
		return nil, false
	}
	sel, ok := star.X.(*ast.SelectorExpr)
	if !ok {
		return nil, false
	}
	pkg, ok := sel.X.(*ast.Ident)
	if !ok || pkg.Name != "model" {
		return nil, false
	}
	modelType := sel.Sel.Name
	helper := "get" + modelType + fn.Name.Name + "Resolver"

	args := []ast.Expr{ast.NewIdent(objName)}
	for _, p := range fn.Type.Params.List[2:] {
		for _, n := range p.Names {
			args = append(args, ast.NewIdent(n.Name))
		}
	}
	return returnCallArgs(helper, args), true
}

func returnCall(name string) *ast.BlockStmt {
	return returnCallArgs(name, nil)
}

func returnCallArgs(name string, args []ast.Expr) *ast.BlockStmt {
	return &ast.BlockStmt{
		List: []ast.Stmt{
			&ast.ReturnStmt{
				Results: []ast.Expr{
					&ast.CallExpr{
						Fun:  ast.NewIdent(name),
						Args: args,
					},
				},
			},
		},
	}
}
