---
# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
apiVersion: v2
name: tenancy-datamodel
description: Tenancy Datamodel
type: application
version: 0.3.1
appVersion: "1.2.1"
annotations: {}
