# SPDX-FileCopyrightText: 2025 Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
---
{{- $allNamespaces := dict }}
{{- if .Values.core.namespace }}
  {{- $_ := set $allNamespaces .Values.core.namespace true }}
{{- end }}
{{- range .Values.bootstrap.providers }}
  {{- if .namespace }}
    {{- $_ := set $allNamespaces .namespace true }}
  {{- end }}
{{- end }}
{{- range .Values.controlplane.providers }}
  {{- if .namespace }}
    {{- $_ := set $allNamespaces .namespace true }}
  {{- end }}
{{- end }}
{{- range $ns, $_ := $allNamespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
---
{{- end }}
