---
# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: tenancy-api-mapping
description: A Helm chart for bootstrapping the 'tenancy-api-mapping'
type: application
version: 0.5.0
appVersion: "1.4.0"
