apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nexus-api-gw
  labels:
    app.kubernetes.io/name: nexus-api-gw
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  api-gw-config: |
    {{- toYaml .Values.config | nindent 4 }}
---
{{- if .Values.nexusK8sProxyKubeconfig.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nexus-k8s-proxy-kubeconfig
  labels:
    app.kubernetes.io/name: nexus-k8s-proxy-kubeconfig
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: http://{{ .Release.Name }}-nexus-k8s-proxy:80
        insecure-skip-tls-verify: true
      name: dummy-cluster
    contexts:
    - context:
        cluster: dummy-cluster
        user: dummy-user
      name: dummy-context
    current-context: dummy-context
    users:
    - name: dummy-user
      user: {}
{{- end }}

