apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nexus-api-gw
  labels:
    app.kubernetes.io/name: nexus-api-gw
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  api-gw-config: |
    {{- $cfg := omit .Values.config "graphql" }}
    {{- $gql := .Values.config.graphql | default dict }}
    {{- if $gql.enabled }}
    {{- $svc := $gql.service | default (printf "%s-nexus-graphql" .Release.Name) }}
    {{- $ns := $gql.namespace | default .Release.Namespace }}
    {{- $port := $gql.port | default 80 }}
    {{- $_ := set $cfg "graphqlBackend" (printf "http://%s.%s.svc.cluster.local:%v" $svc $ns $port) }}
    {{- end }}
    {{- toYaml $cfg | nindent 4 }}
---
{{- if .Values.nexusK8sProxyKubeconfig.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nexus-k8s-proxy-kubeconfig
  labels:
    app.kubernetes.io/name: nexus-k8s-proxy-kubeconfig
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config: |
    apiVersion: v1
    kind: Config
    clusters:
    - cluster:
        server: http://{{ .Release.Name }}-nexus-k8s-proxy:80
        insecure-skip-tls-verify: true
      name: dummy-cluster
    contexts:
    - context:
        cluster: dummy-cluster
        user: dummy-user
      name: dummy-context
    current-context: dummy-context
    users:
    - name: dummy-user
      user: {}
{{- end }}

