apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nexus-api-gw
  labels:
    app.kubernetes.io/name: nexus-api-gw
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: nexus-api-gw
spec:
  selector:
    app.kubernetes.io/name: nexus-api-gw
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: nexus-api-gw
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.config.server.httpPort | default 80 }}
