---
# SPDX-FileCopyrightText: 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

global:
  localSubModsDir: "repos"
  localDownloadsDir: "downloads"
  specOutputDir: "openapispecs/generated"
  apimappingconfigcrsdir: "apimappingconfigcrs"
  defaultMaxItems: 100  # Default maxItems for arrays without explicit limits

  servers:
    - url: "{apiRoot}"
      variables:
        - key: "apiRoot"
          value: "https://<multitenancy-gateway-host>"
