# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

version = 1

[[annotations]]
path = [
  "README.md",
  "VERSION",
  "go.sum",
  "package-lock.json",
  "package.json",

  "downloads/*", # these are sourced from SwaggerHub or other locations
]

precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2025 Intel Corporation"
SPDX-License-Identifier = "Apache-2.0"
